### ISSUE TITLE
request: interoperate with remix, i need expose a func to generate account

### ISSUE THREAD

**Issue by xiaods** [GeekBerry/js-conflux-sdk#4]
currently Conflux class only expose one func: 
```js
Account(privateKey) {
    return new Account(privateKey);
  }
```
i want to expose internal func random to help remix to generate testing account to contract all

**Comment by xiaods** [comment]
in Account , i found a random func. it can do it with my request.

**Comment by GeekBerry** [comment]
Account.random()

**Comment by xiaods** [comment]
@GeekBerry Hey Geek, in Remix nodejs package, the js is npm install js-conflux-sdk.
i only require the index.js. the root Class is Conflux, i have no chance to expose the Account.

**Comment by GeekBerry** [comment]
is this worked `import Account from 'js-conflux-sdk/src/Account'` ?
I worry export Account to index.js is not a good idea cause:
```
const Conflux  = require('js-conflux-sdk');
const cfx = new Conflux(...);

Conflux.Account // is a class
cfx.Account // is a method which i don't want to lowercase the name, (for diff from RPC method)
```

**Comment by xiaods** [comment]
@GeekBerry Thanks for your clarify the reason. i will cover that .
