### ISSUE TITLE
help unknow error for send contract tx to testnet

### ISSUE THREAD

**Issue by xiaods** [GeekBerry/js-conflux-sdk#5]
use js-conflux-sdk to deploy contract ,came across a error. cloud you do me a favor.

context:
```
  const response = await deployContract.constructor(orderedParams).sendTransaction(tx).confirmed()
 ```
it report error
<img width="1102" alt="屏幕快照 2020-02-03 下午12 23 08" src="https://user-images.githubusercontent.com/37678/73625472-f8f7c600-467f-11ea-84c8-e86bc018123a.png">

https://github.com/xiaods/conflux-remix/blob/master/src/api/index.js#L80

**Comment by GeekBerry** [comment]
https://github.com/GeekBerry/js-conflux-sdk/blob/master/api.md#confluxsendtransaction

**Comment by GeekBerry** [comment]
i guess you migth need to store **Address to Account map** manual to cfx or some stateful object,
cause SDK do not manager a virtual wallet like eth.

**Comment by xiaods** [comment]
@GeekBerry got it. let me cover that.

**Comment by GeekBerry** [comment]
As a user, do you think is a good idea to manager a wallet inner SDK which check address in `from` field to get and sign Transaction auto?
In the very begining, I want SDK to be pure function and without any state. But now i am confused and want some feed back.

**Comment by xiaods** [comment]
@GeekBerry i have console.log the account , it use random to generate account, it already have private key with public address.

https://github.com/xiaods/conflux-remix/blob/master/src/api/index.js#L80

your comments:
```
You migth need ensure txMetadata.account is a Account instance otherwise you need sign transation manual.
```
why it have not invoke the cfx_sendRawTransaction.  

====
your question:
----
As a user, do you think is a good idea to manager a wallet inner SDK which check address in from field to get and sign Transaction auto?
In the very begining, I want SDK to be pure function and without any state. But now i am confused and want some feed back.

feedback:
conflux-remix is developer ide. so you need a convenient way to manage the wallet. i don't think currently sdk need concern the usage prefer. right now keep the function here. if more request coming, we can discussion later.

as user, we need more practice sample on it. so don't worry on it.

**Comment by GeekBerry** [comment]
Send transaction check is [here](https://github.com/GeekBerry/js-conflux-sdk/blob/master/src/Conflux.js#L699). Are you sure `options.from instanceof Account` is true.
Account override the magic method `toString` and return account.address, is there any `stringify and  parser` operate to let `from` to be string?

**Comment by xiaods** [comment]
@GeekBerry the console.log is true.  and i explicit construct option , it always get error.
https://github.com/xiaods/conflux-remix/blob/master/src/api/index.js#L82

it weird.

**Comment by xiaods** [comment]
@GeekBerry i know the reason.  the contract assemble steps i have not clear and understand.
i know the send contract tx ,i can directly use sendRawTransaction.
but [here](https://github.com/GeekBerry/js-conflux-sdk/blob/master/src/Conflux.js#L702) is associate with cfx instance. not contract instance.

i have not found any way to assemble contract code to tx. any way can show me the code, let me clear the curious.

**Comment by xiaods** [comment]
if you know the plain  rpc invoke contract code sample.also welcome.

**Comment by xiaods** [comment]
i got it. the js-conflux-sdk's Contract class, have not defined the sendRawTransaction

**Comment by xiaods** [comment]
i got it. and construct the contract options. and send successful.

**Comment by xiaods** [comment]
@GeekBerry i read here:
https://github.com/GeekBerry/js-conflux-sdk/blob/master/src/contract/ContractFunction.js#L25

and you hint [code](https://github.com/GeekBerry/js-conflux-sdk/blob/master/src/Conflux.js#L699) is relate to cfx. it not bind contract.  this is root concern for me.

please guide me.

**Comment by xiaods** [comment]
recap:
1、** cfx_sendTransaction** not suport
2、contract method sendTransaction  invoke  cfx.sendTransaction

it let user confuse.

**Comment by GeekBerry** [comment]
1. "cfx_sendTransaction" not support  yet and will not be support soon.
2. contract method just compile arguments to `data` for user, and call `cfx_sendTransaction` in the end.
====
* user could call rpc by: `await cfx.provider.call('<method name>', ...args)` such as `await cfx.provider.call('cfx_getBlockByHash', '0x123456...', true);` or `await cfx.provider.call('cfx_sendRawTransaction', '0x byte code')`

Do you have any other contact way like wechat, we have a  "Conflux JavaScript API" wechat group, yanpei or me (Haizhou@conflux-chain.org) could invite you.

**Comment by xiaods** [comment]
i have resolve by use cfx_sendRawTransaction.

**Comment by xiaods** [comment]
@GeekBerry yanpei know i wechat account, you can ask yanpei to add my account to the wechat group.
